### ISSUE TITLE
Define and implement an API

### ISSUE THREAD

**Issue by ryeng** [la1k/libpredict#1]
Currently, all symbols in the library are exported, and there's no symbol naming policy. The API must be defined and documented.

All symbols that are part of the API must start with a "predict_" prefix to avoid namespace conflicts with other libraries. The list of exported symbols must be restricted to those symbols to avoid internal symbols leaking out and cluttering the namespace.

When this is done, bump the ABI version to 1.0.0.

**Comment by bjorgan** [comment]
Fixed by 90e3c582f3fec8da8280b0c1102bcae2f8bc64d4 and 579766eba591dbe5e5609709013285bd681d7826.

**Comment by ryeng** [comment]
The version number bump is issue #25.
