### ISSUE TITLE
Is there a specified version for ARM Cortex M

### ISSUE THREAD

**Issue by Ishakengineer** [la1k/libpredict#107]
I want to run Libpredict on stm32l151 and i want to plot the position of satellite on the map, but the part of plotting is developed on python and so it can't be run on ARM MCU

**Comment by ryeng** [comment]
Libpredict itself doesn't do plotting, and it's not on the roadmap. The Python script that plots satellite passes is just an example application. If Python doesn't run on your platform, you may use other plotting tools that do exist for that platform.
