### ISSUE TITLE
Tag all non-cleanroom functions with copyright information.

### ISSUE THREAD

**Issue by thomasing** [la1k/libpredict#19]
Tag all functions with '\copyright GPLv2+' as long as they still contains bits from old predict project, and thus cannot be considered as clean-room implementations.

**Comment by bjorgan** [comment]
I have tagged all public functions where this is a concern (commit ac1ea99393cde7f9a594f20ea2e19e749a643d98). Should this also include private functions?

**Comment by ryeng** [comment]
@bjorgan Yes.

**Comment by bjorgan** [comment]
Private API should also be tagged correctly now, but @thomasing might want to check whether I have mislabeled anything/missed labeling something before we close this issue.

**Comment by bjorgan** [comment]
Fixed by 930c8b1.
