### ISSUE TITLE
Minimal header files

### ISSUE THREAD

**Issue by ryeng** [la1k/libpredict#2]
Make the header files used by client applications minimal, covering only the defined API. Internal symbols must be in private header files that aren't installed by make install.

**Comment by ryeng** [comment]
Can you please have a look at this, @thomasing? We have to do this with an eye toward bug #1, but I think it makes sense to limit the header files first, thereby defining what to include, and then go over it all and change prefixes, rename and make it look pretty.

**Comment by thomasing** [comment]
Fixed ab1a0b9
