### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by bjorgan** [la1k/libpredict#21]
Need tests for checking correctness of libpredict. Given specific TLE and a set of timestamps, generate file(s) with calculated properties from original predict. Write functions to test the developed library functions against the timestamps and properties in this file. 

For AOS/LOS/moonrise/sunrise, can also run some kind of sanity check? Loop through the orbit, check if AOS and LOS actually happens, or passes are missed, and calculate how accurate the results are. Call AOS/LOS repeatedly at different times to see whether the results fall within a specified threshold.

**Comment by bjorgan** [comment]
We now (as of commit 2917970b429681) have tests and (test data generation from predict) against: 
- Predicted orbit of satellites (longitude, latitude, altitude)
- Predicted observation of satellites (azimuth, elevation)
- Predicted observation of sun (azimuth, elevation)
- Predicted observation of moon (azimuth, elevation)
- Sanity check of AOS/LOS for a given satellite (predict is not involved, loops through the times to see whether they make sense with respect to the behavior of the orbit)

Are any more tests needed? 

Still remaining: Need to find satellites from which we can generate good test cases. SGP4, SDP4, geostationary, difficult orbits, ... .

**Comment by ryeng** [comment]
Fixed by a45fd8caddcce7b2fd7ca1095ccbdd4a577d4d5e.
