### ISSUE TITLE
Separation of input/output in struct orbit

### ISSUE THREAD

**Issue by bjorgan** [la1k/libpredict#22]
Split orbit parameters and time-dependent, predicted values into separate structs. 

Most functions will mostly keep the same number of function arguments since they either use only the predicted values or the fixed orbit parameters.

**Comment by bjorgan** [comment]
Constifying the fixed parts of orbit_t can be challenging due to deep_arg in struct _sdp4. Will need to refactor the code, but [a newer version](https://celestrak.com/publications/AIAA/2006-6753) of the SGP4 model is also available. We will in any case need to implement the model from an original source at some point.

**Comment by ryeng** [comment]
See also issue #31.

**Comment by bjorgan** [comment]
Fixed in commit 1a08baf10f59bf4019beb1759dad97ba247fc07a.
