### ISSUE TITLE
Phase and orbit number

### ISSUE THREAD

**Issue by bjorgan** [la1k/libpredict#30]
libpredict is missing functions to calculate some properties which are displayed in predict (and will be displayed in flyby):
- Modulo 256 phase (P-screen)
- Phase (T-screen, does not seem to be the same as the one above)
- Orbit (P-screen, seems to be variable with time)

**Comment by ryeng** [comment]
Move to 2.0.0 milestone if it turns out predict.h is changed in an incompatible way.

**Comment by ryeng** [comment]
Tagging as both major and minor number bump to account for uncertainty in how the implementation will be. Could turn out to be either.
