### ISSUE TITLE
src/julian_date.c needs "#include <time.h>" for gmtime_r

### ISSUE THREAD

**Issue by yurivict** [la1k/libpredict#99]
But on BSD it only works if included before ```#define _POSIX_C_SOURCE 1```.

**Comment by ryeng** [comment]
You're right. I don't know why this has worked on Linux.

**Comment by ryeng** [comment]
I've made a pull request, but I don't have a FreeBSD box a the moment. It would be really helpful if you or someone else could test this on FreeBSD and report back.
